# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_opening_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getterprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='getterrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.AddField(
            model_name='opening',
            name='desired_fee',
            field=models.PositiveSmallIntegerField(default=500),
        ),
        migrations.DeleteModel(
            name='GetterProfile',
        ),
        migrations.DeleteModel(
            name='GetterRating',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
